### ISSUE TITLE
Campaigns that drove the maximum first touches were not included in the final recommendation for campaign re-investment

### ISSUE THREAD

**Issue by JagaRamesh** [ebulls595/capstoneproject#1]
In the conclusion, the campaigns that drove the maximum first touches needs to be included as well. Cool T-shirts can re-invest in the following top campaigns that drove 91% of first touches 
1. interview-with-cool-tshirts-founder
2. getting-to-know-cool-tshirts
3. ten-crazy-cool-tshirts-facts
and the following campaigns that drove maximum last touches to increase overall purchase
4. weekly-newsletter
5. retargetting-ad

**Comment by ebulls595** [comment]
Must have missed it. Thanks for the feedback
