### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by JagaRamesh** [ebulls595/capstoneproject#2]
Rubric Score
Criteria 1: Report
* Score Level: 4 (Exceeds Expectations)
* Comment(s): Excellent presentation. All questions are addressed . The SQL results and the text interpretations are organized neatly in every slide.

Criteria 2: Query Accuracy
* Score Level: 4 (Exceeds Expectations)
* Comment(s): All queries accurately retrieve the data intended.

Criteria 3: Query Formatting
* Score Level: 4 (Exceeds Expectations)
* Comment(s): Queries are formatted according to the SQL style guide..

Criteria 4: Understanding underlying concepts and terminology
* Score Level: 3 (Meets Expectations)
* Comment(s): Good understanding of the concept, user journey and the campaigns. The final campaign recommendation does not include the first touch campaigns. I have created a separate issue for the same.

Overall Score: 15/16
Awesome Job. Accurate coding with proper SQL formatting. The presentation is neat and communicates the results, analysis and the recommendation effectively. In the conclusion, the campaigns that drove the traffic to CoolTShirts (first touches) needs to be included as well. Well done!!

**Comment by ebulls595** [comment]
AHHH Thank you so much! It was a lot of fun learning!
